sudo: required
services:
  - docker
script:
  - docker build -t price-dashboard_nginx:latest ./nginx
  - docker build -t price-dashboard_web:latest ./services/web
  - docker build -t price-dashboard_user:latest ./services/user
  - docker build -t price-dashboard_prices:latest ./services/prices
  - docker build -t price-dashboard_promotions:latest ./services/promotions
  - docker build -t price-dashboard_upgrade-rules:latest ./services/upgrade-rules
