sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
before_script:
  # Log in to the docker CLI
  - bash ./scripts/login-dockerhub.sh $DOCKER_PASSWORD $DOCKER_ID
script:
  # Build docker images
  - bash ./scripts/build-docker-img.sh $DOCKER_NAME $SHA
  # Take hose images and push them to docker hub
  - bash ./scripts/push-img-to-dockerhub.sh $DOCKER_NAME $SHA
deploy:
  provider: elasticbeanstalk
  region: <us-west-1>
  app: <multi-docker>
  env: <S3-env>
  bucket_name: <S3 bucket elasticbeanstalk-us-west-1-131313>
  bucket_path: <docker-S3-bucket>
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
notifications:
  email: false
