apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: user
  template:
    metadata:
      labels:
        component: user
    spec:
      containers:
        - name: user
          image: daniellin9406/price-dashboard_user
          ports:
            - containerPort: 4999
          env:
            - name: PORT
              value: "4999"
            - name: NODE_ENV
              value: production
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: clientid
                  key: CLIENT_ID
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: clientsecret
                  key: CLIENT_SECRET
            - name: REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: redirecturi
                  key: REDIRECT_URI
