apiVersion: apps/v1
kind: Deployment
metadata:
  name: upgrade-rules-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: upgrade-rules
  template:
    metadata:
      labels:
        component: upgrade-rules
    spec:
      containers:
        - name: upgrade-rules
          image: {{DOCKER_NAME}}/price-dashboard_upgrade-rules
          ports:
            - containerPort: 5002
          env:
            - name: PORT
              value: "5002"
            - name: NODE_ENV
              value: production
            - name: REDIS_HOST_PROD
              value: redis-cluster-ip-service
            - name: REDIS_PORT_PROD
              value: "6379"
            - name: DATABASE_URL_PROD
              valueFrom:
                secretKeyRef:
                  name: databaseurlprod
                  key: DATABASE_URL_PROD
            - name: AUTH_HOST_PROD
              value: user-cluster-ip-service
            - name: AUTH_PORT_PROD
              value: "4999"
            - name: AUTH_VER_PROD
              value: v1
