apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
sepc:
  acme:
    server: https://acem-v02.api.letsencrypt.org/directory
    email: ""
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
